services:
  - type: web
    name: chexbot-site
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: OPENAI_KEY
        fromDotEnv: true
      - key: GOOGLE_API_KEY
        fromDotEnv: true
      - key: GOOGLE_CSE_ID
        fromDotEnv: true
      - key: CONSUMER_KEY
        fromDotEnv: true
      - key: CONSUMER_SECRET
        fromDotEnv: true
      - key: ACCESS_TOKEN
        fromDotEnv: true
      - key: ACCESS_SECRET
        fromDotEnv: true
      - key: BEARER_TOKEN
        fromDotEnv: true

  - type: worker
    name: chexbot-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python chexbot.py"
    plan: free
    envVars:
      - key: OPENAI_KEY
        fromDotEnv: true
      - key: GOOGLE_API_KEY
        fromDotEnv: true
      - key: GOOGLE_CSE_ID
        fromDotEnv: true
      - key: CONSUMER_KEY
        fromDotEnv: true
      - key: CONSUMER_SECRET
        fromDotEnv: true
      - key: ACCESS_TOKEN
        fromDotEnv: true
      - key: ACCESS_SECRET
        fromDotEnv: true
      - key: BEARER_TOKEN
        fromDotEnv: true
